# Based on https://github.com/PojavLauncherTeam/angle/blob/main_old/.github/workflows/build-android-vulkan.yml

name: ANGLE Build CI

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm", "arm64", "x86", "x64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest

    steps:
      - name: Get ANGLE
        uses: actions/checkout@v5
        with:
          path: 'angle'

      - name: Build ANGLE
        shell: bash
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=`pwd`/depot_tools:$PATH
          echo $PATH
          cd angle
          vpython scripts/bootstrap.py
          gclient sync
          gn gen out/Android-${{matrix.arch}}
          autoninja -C out/Android-${{matrix.arch}}

      - name: Upload ANGLE
        uses: actions/upload-artifact@v4
        with:
          name: angle-libs-${{matrix.arch}}
          path: |
            angle/out/Android-${{matrix.arch}}/libGLESv2_angle.so
            angle/out/Android-${{matrix.arch}}/libEGL_angle.so
